import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen">
        <div className="text-xl flex justify-around">
          <p className="mr-2 border-2"> darkness</p>
          <p className="mr-2 border-2"> darknezz</p>
        </div>
      </main>

      <footer className="flex justify-center bg-slate-300 py-5">
        <p>Footer</p>
      </footer>
    </div>
  );
}
