import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen pt-9 bg-lime-200">
        <div className="flex flex-col">
          <div className="flex justify-center">
            <div className="bg-slate-200 rounded-full p-1">
              <Image
                src={"/iconTerraria.png"}
                alt="Picture of the author"
                width={90}
                height={90}
                style={{ borderRadius: "90px" }}
              />
            </div>
          </div>
          <div className="text-center text-xl font-semibold p-2">
            <p>Arthur Efraim</p>
            <p className="font-normal text-sm">Front-end Developer</p>
          </div>

          <div className="flex items-center content-between justify-evenly flex-col mt-9 font-semibold mx-4 space-y-4 text-white">
            <a
              href="https://github.com/efraimarthur"
              className="border w-full text-center py-4 bg-teal-700 rounded-md"
            >
              Github
            </a>
            <a
              href="https://www.instagram.com/thur.ion/"
              className="border w-full text-center py-4 bg-teal-700 rounded-md"
            >
              Instagram
            </a>
            <a
              href="https://www.linkedin.com/in/arthurefraim/"
              className="border w-full text-center py-4 bg-teal-700 rounded-md"
            >
              LinkedIn
            </a>
            <a
              href="https://arthurefraim.vercel.app/"
              className="border w-full text-center py-4 bg-teal-700 rounded-md"
            >
              Web Profile
            </a>
          </div>
        </div>
      </main>

      <footer className="flex justify-center py-5 bg-lime-200">
        <p>Footer?</p>
      </footer>
    </div>
  );
}
