import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen pt-9 bg-lime-200">
        <div className="flex flex-col">
          <div className="flex justify-center">
            <div className="bg-slate-200 rounded-full p-1">
              <Image
                src={"/iconTerraria.png"}
                alt="Picture of the author"
                width={90}
                height={90}
                style={{ borderRadius: "90px" }}
                // blurDataURL="data:..." automatically provided
                // placeholder="blur" // Optional blur-up while loading
              />
            </div>
          </div>
          <div className="text-center text-xl font-semibold p-2">
            <p>Arthur Efraim</p>
            <p className="font-normal text-sm">Front-end Developer</p>
          </div>

          <div className="flex justify-center mt-6"></div>
        </div>
      </main>

      <footer className="flex justify-center bg-slate-300 py-5">
        <p>Footer</p>
      </footer>
    </div>
  );
}
